server:
  port: 9527


spring:  application:    name: microservicecloud-zuul-gateway
eureka:  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    instance-id: gateway    prefer-ip-address: true
zuul: 
  prefix: /demo
  ignored-services: microservicecloud-dept 
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
info:
  app.name: demo-microservicecloud
  company.name: www.demo.com
  build.artifactId: microservicecloud-zuul-gateway
  build.version: 0.0.1-SNAPSHOT
   